---

# Centos 更新 安装基础软件工具等操作
- block:
  - name: System Upgrade
    yum: name=* state=latest

  - name: Install EPEL
    yum:
      name: epel-release
    # template:
    #   src: '{{item.src}}'
    #   dest: '{{item.dest}}'
    # with_items:
    #   - {src: epel.repo.jinja2,dest: /etc/yum.repos.d/epel.repo}
    #   - {src: 'RPM-GPG-KEY-EPEL-{{ansible_distribution_version}}',dest: /etc/pki/rpm-gpg/}


  - name: Disable SELinux
    selinux:
      state: disabled

  - name:  temporarily disable Selinux
    shell: setenforce 0 

  - name: Install Common Software
    yum: 
      name: [mosh,yum-utils,wget,openssl,unzip,bzip2,expect,at,vim, screen,pwgen,git, htop, yum-cron,ImageMagick, goaccess,MySQL-python,python-pip]
      state: installed
    
  - name: Configuration yum-cron
    copy: src=yum-cron.conf dest=/etc/yum/

  - name: Start yum-cron
    service: name=yum-cron state=started enabled=yes
  
  when: ansible_distribution == 'CentOS'

# Ubuntu 更新 安装基础软件工具等操作
- block:
  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      update_cache: yes
      force_apt_get: True
      autoremove: yes

  - name: Install Common Software
    apt: 
      name: [mosh,curl,gnupg2,ca-certificates,lsb-release,wget,openssl,unzip,bzip2,expect,at,vim,screen,pwgen,git,htop,imagemagick,goaccess,python3-mysqldb,python-mysqldb,python-pip,python3-pip,unattended-upgrades,python3-pexpect,python-pexpect]
      state: latest
      force_apt_get: True
      allow_unauthenticated: yes

  - name: Configuration unattended-upgrades
    copy: src=20auto-upgrades dest=/etc/apt/apt.conf.d/
  
  when: ansible_distribution == 'Ubuntu'

- block:
  - name: Create swap Space
    command: dd if=/dev/zero of=/mnt/swap bs=256M count=8

  - name: Make swap
    command: mkswap /mnt/swap

  - name: Action swap
    command: swapon /mnt/swap
  
  - name: Add to fstab
    lineinfile:
        dest: /etc/fstab
        regexp: '/mnt/swap'
        line: "/mnt/swap swap swap defaults 0 0"
        state: present

  when: (ansible_swaptotal_mb == 0) and (cloud != 'azure')

- block:
  - name: ResourceDisk EnableSwap
    lineinfile:
      dest: /etc/waagent.conf
      regexp: 'ResourceDisk.EnableSwap=n'
      line: "ResourceDisk.EnableSwap=y"
      state: present

  - name: ResourceDisk SwapSizeMB
    lineinfile:
      dest: /etc/waagent.conf
      regexp: 'ResourceDisk.SwapSizeMB=0'
      line: "ResourceDisk.SwapSizeMB=2048"
      state: present
  when: cloud == 'azure'


- name: Set swapiness
  sysctl:
    name: vm.swappiness
    value: "10"


- name: Fix No space left on device
  sysctl:
    name: fs.inotify.max_user_watches
    value: "262144"

- block:
  - name: AWS Configure
    apt:
      name: ec2-instance-connect
      update_cache: yes

  - name: Start ec2-instance-connect
    service:
      name: ec2-instance-connect
      state: started
      enabled: yes
  when: cloud == 'aws' and ansible_distribution == 'Ubuntu'

- block:
  - name: AWS Configure
    yum:
      name: ec2-instance-connect
  
  - name: Start ec2-instance-connect
    service:
      name: ec2-instance-connect
      state: started
      enabled: yes

  when: cloud == 'aws' and ansible_distribution == 'Centos'

- name: Create Dir
  file:
    path: '/data/{{item}}'
    state: directory
  with_items:
    - logs
    - config
    - cert